import { NextResponse } from "next/server";
import useGlobalStore from "@/store/globalStore";

interface BookingDTO {
  id?: string;
  status: string;
  bookedOn: Date;
  tourist: string[];
  tour?: string;
  tourPackage?: string;
}

export async function POST(request: Request) {
  const body = await request.json();
  const { setBookings, bookings } = useGlobalStore.getState();

  const newBooking: BookingDTO = {
    id: Date.now().toString(), // This should be generated by the database in a real application
    status: body.status,
    bookedOn: new Date(body.bookedOn),
    tourist: body.tourist,
    tour: body.tour,
    tourPackage: body.tourPackage,
  };

  // In a real application, you would save this to a database
  // For now, we'll just add it to the store
  setBookings([...(bookings || []), newBooking]);

  return NextResponse.json({ success: true, booking: newBooking });
}
